export const MenzaTokens = {
  colors: {
    canvas: '#FAF7F2',
    canvasStrong: '#F5EBDD',
    surface: '#FFFFFF',
    surfaceMuted: '#FFF9F2',
    text: '#1F2937',
    textMuted: '#5C4E3D',
    textSubtle: '#7C6F62',
    brand: '#DE8626',
    brandDark: '#B84D00',
    brandSoft: '#FFF0DE',
    border: '#E7E1DA',
    divider: '#E9E3DC',
    success: '#17845A',
    successSoft: '#E4F5EC',
    warning: '#FEA619',
    warningSoft: '#FFF3DC',
    danger: '#DC2626',
    dangerSoft: '#FEE2E2',
    info: '#346CB0',
    infoSoft: '#EAF2FD',
  },
  typography: {
    display: 34,
    title: 26,
    heading: 20,
    body: 16,
    bodySmall: 14,
    label: 12,
    button: 17,
    weight: {
      regular: '400' as const,
      medium: '500' as const,
      semibold: '600' as const,
      bold: '700' as const,
      heavy: '800' as const,
    },
  },
  spacing: {
    xxs: 4,
    xs: 8,
    sm: 12,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  radius: {
    sm: 10,
    md: 16,
    lg: 24,
    pill: 999,
  },
  border: {
    width: 1,
    focusWidth: 2,
  },
  shadows: {
    card: {
      shadowColor: '#3C2F00',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 16,
      elevation: 4,
    },
    button: {
      shadowColor: '#D96B14',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 10,
      elevation: 3,
    },
  },
  iconSize: {
    xs: 14,
    sm: 18,
    md: 22,
    lg: 28,
  },
} as const;
