export const Spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 20,
  xl: 24,
  xxl: 32,
  xxxl: 48,
  borderRadius: {
    xs: 6,
    sm: 8,
    buttonSmall: 12,
    md: 12,
    buttonStandard: 16,
    lg: 16,
    card: 20,
    cardLarge: 24,
    xl: 20,
    quickAction: 20,
    floatingNav: 36,
    full: 999,
  },
  elevation: {
    card: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 10,
      elevation: 4,
    },
    buttonPrimary: {
      shadowColor: '#4F46E5',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.4,
      shadowRadius: 18,
      elevation: 6,
    },
    buttonAccent: {
      shadowColor: '#F5A623',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.4,
      shadowRadius: 18,
      elevation: 6,
    },
    buttonDanger: {
      shadowColor: '#EF4444',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.4,
      shadowRadius: 18,
      elevation: 6,
    },
    buttonSuccess: {
      shadowColor: '#10B981',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.4,
      shadowRadius: 18,
      elevation: 6,
    },
  },
};
