/**
 * MENZA TERMS & CONDITIONS, RULES & REGULATIONS
 * Source: MENZA RULE AND REGULATION.docx
 * Operated By: QUBENEXUS TECHNOLOGIES PRIVATE LIMITED
 */

export interface LegalSection {
  id: number;
  title: string;
  category: 'general' | 'services' | 'financial' | 'compliance' | 'legal';
  icon: string;
  summary: string;
  content: string[];
}

export const MENZA_LEGAL_METADATA = {
  appName: 'Menza',
  tagline: 'Smart • Simple • Serve',
  title: 'Terms & Conditions, Rules & Regulations',
  effectiveDate: '31/08/2026',
  website: 'www.menza.in',
  operatedBy: 'QUBENEXUS TECHNOLOGIES PRIVATE LIMITED',
  address: 'Plot No 31, Sage Suncity Phase-2, Bagroda, Bhopal, Madhya Pradesh, PIN Code: 462026',
  supportEmail: 'support@menza.in',
  supportPhone: '+91 9713034109',
  jurisdiction: 'Bhopal, Madhya Pradesh, India',
};

export const MENZA_LEGAL_CATEGORIES = [
  { key: 'all', label: 'All Articles' },
  { key: 'general', label: 'Overview & Reg.' },
  { key: 'services', label: 'Services & Orders' },
  { key: 'financial', label: 'Billing & Wallet' },
  { key: 'compliance', label: 'Responsibilities' },
  { key: 'legal', label: 'Legal & Liability' },
] as const;

export const MENZA_LEGAL_SECTIONS: LegalSection[] = [
  {
    id: 1,
    title: '1. Introduction',
    category: 'general',
    icon: 'Info',
    summary: 'Overview of the Menza restaurant technology and management platform.',
    content: [
      'Menza is a restaurant technology and management platform providing services such as restaurant billing, POS, QR ordering, menu management, table management, order management, payment integration, customer management, reporting and other related technology services.',
      'By registering with or using Menza, the Restaurant, Merchant, Customer or other user agrees to comply with these Terms & Conditions, Rules and Regulations.',
    ],
  },
  {
    id: 2,
    title: '2. User / Restaurant Registration',
    category: 'general',
    icon: 'UserCheck',
    summary: 'Account creation, credential confidentiality, and user accountability.',
    content: [
      '1. The Restaurant/Merchant must provide accurate and complete information during registration.',
      '2. The Restaurant is responsible for keeping its login credentials confidential.',
      '3. One account must not be shared with unauthorized persons.',
      '4. Menza may suspend or terminate an account if incorrect, fraudulent or misleading information is provided.',
      '5. The Restaurant is responsible for all activities performed through its account.',
    ],
  },
  {
    id: 3,
    title: '3. Menza Services',
    category: 'services',
    icon: 'Sparkles',
    summary: 'Scope of POS, billing, digital menu, QR ordering, analytics, and other provided tools.',
    content: [
      'Depending upon the selected plan, Menza may provide:',
      '• POS and restaurant billing',
      '• Digital menu',
      '• QR code ordering',
      '• Table management',
      '• Kitchen/order management',
      '• Online and offline order management',
      '• Payment gateway integration',
      '• Customer management',
      '• Sales and business reports',
      '• Inventory-related features',
      '• Offers and promotional tools',
      '• Digital receipts/invoices',
      '• Restaurant analytics',
      '• Other services introduced by Menza from time to time',
      'Menza reserves the right to add, modify, suspend or discontinue any feature or service.',
    ],
  },
  {
    id: 4,
    title: '4. Subscription & Service Charges',
    category: 'financial',
    icon: 'CreditCard',
    summary: 'Plan fees, setup charges, GST taxes, non-refundability, and price revisions.',
    content: [
      '1. The Restaurant may be required to pay subscription, setup, transaction, service or other applicable charges.',
      '2. Applicable charges will be communicated before activation of the relevant paid service.',
      '3. Taxes such as GST, where applicable, shall be charged separately.',
      '4. Subscription fees are generally non-refundable unless specifically agreed otherwise.',
      '5. Menza may revise its pricing with reasonable prior notice.',
    ],
  },
  {
    id: 5,
    title: '5. Orders & Billing',
    category: 'services',
    icon: 'Receipt',
    summary: 'Menu accuracy, bill reflections, customer dispute resolution, and technology provider status.',
    content: [
      '1. The Restaurant is responsible for the correctness of menu items, prices, taxes, discounts and other information entered into the system.',
      '2. The Restaurant must ensure that the bill generated through Menza accurately reflects the customer\'s order.',
      '3. Any dispute relating to food quality, quantity, preparation, delivery or restaurant service shall primarily be resolved by the Restaurant.',
      '4. Menza acts as a technology/service provider and does not manufacture or supply food.',
    ],
  },
  {
    id: 6,
    title: '6. Payment Gateway & Transactions',
    category: 'financial',
    icon: 'IndianRupee',
    summary: 'Third-party payment gateways, bank charges, payment failure rules, and chargeback reconciliation.',
    content: [
      '1. Payments may be processed through third-party payment gateways or banking partners.',
      '2. Menza does not guarantee uninterrupted availability of any third-party payment service.',
      '3. Payment gateway charges, banking charges and applicable taxes may apply.',
      '4. In case of payment failure, reversal, refund or chargeback, the transaction shall be subject to the rules of the concerned payment gateway/bank.',
      '5. Menza may assist in transaction reconciliation but shall not be responsible for failures caused by banks, payment gateways, networks or other third parties.',
    ],
  },
  {
    id: 7,
    title: '7. Menza Wallet / Merchant Wallet',
    category: 'financial',
    icon: 'Wallet',
    summary: 'Permitted wallet usage, automated service deductions, electronic adjustments, and fraud restrictions.',
    content: [
      'Where the Menza Wallet facility is enabled:',
      '1. Wallet balance may be used only for permitted Menza services or transactions.',
      '2. Wallet balance cannot be treated as a bank account or deposit account.',
      '3. Wallet credits, deductions and adjustments will be recorded electronically.',
      '4. Any applicable service fee or transaction fee may be deducted automatically as disclosed to the Restaurant.',
      '5. Menza may restrict, suspend or close wallet facilities in cases of suspected fraud, misuse or violation of these Terms.',
      '6. Wallet refunds or withdrawals, where permitted, shall be subject to Menza\'s applicable policy and verification requirements.',
    ],
  },
  {
    id: 8,
    title: '8. Restaurant Responsibilities',
    category: 'compliance',
    icon: 'ShieldCheck',
    summary: 'Lawful operation, correct pricing, food safety compliance, licensing, and ethical software usage.',
    content: [
      'The Restaurant shall:',
      '• Provide genuine and lawful information.',
      '• Maintain correct menu and pricing information.',
      '• Comply with applicable food safety, taxation, GST, consumer protection and other laws.',
      '• Maintain required licences and registrations.',
      '• Protect customer information.',
      '• Not use Menza for unlawful or fraudulent activities.',
      '• Not manipulate orders, transactions, ratings or reports.',
      '• Not attempt to reverse engineer, copy or misuse the Menza software.',
    ],
  },
  {
    id: 9,
    title: '9. Customer Data & Privacy',
    category: 'compliance',
    icon: 'Lock',
    summary: 'Legitimate data usage, privacy protection, data collection for service enhancement, and legal compliance.',
    content: [
      '1. Menza may process information required to provide its services.',
      '2. Customer information must be used only for legitimate business purposes.',
      '3. The Restaurant must not misuse, sell or unlawfully disclose customer information.',
      '4. Menza may collect technical, transaction and usage information necessary for operating and improving the platform.',
      '5. Personal data will be handled in accordance with Menza\'s Privacy Policy and applicable laws.',
    ],
  },
  {
    id: 10,
    title: '10. Intellectual Property',
    category: 'legal',
    icon: 'Award',
    summary: 'Ownership of software, trademarks, logos, UI designs, databases, and copyright protections.',
    content: [
      'All software, application interfaces, designs, logos, trademarks, graphics, content, databases, technology and other intellectual property belonging to Menza shall remain the property of Menza or its respective licensors.',
      'No user shall copy, reproduce, modify, distribute, sell or commercially exploit Menza\'s intellectual property without prior written permission.',
    ],
  },
  {
    id: 11,
    title: '11. Prohibited Activities',
    category: 'compliance',
    icon: 'AlertOctagon',
    summary: 'Strict prohibition of illegal actions, fake orders, malware, security bypass, and money laundering.',
    content: [
      'Users shall not:',
      '• Use Menza for illegal activities.',
      '• Create fake orders or transactions.',
      '• Attempt unauthorized access to Menza systems.',
      '• Introduce malware, viruses or harmful code.',
      '• Circumvent security mechanisms.',
      '• Copy or reproduce Menza\'s software.',
      '• Manipulate transaction records.',
      '• Use Menza for money laundering, fraud or other unlawful purposes.',
    ],
  },
  {
    id: 12,
    title: '12. Service Availability',
    category: 'services',
    icon: 'Activity',
    summary: 'Uptime efforts, maintenance windows, third-party network dependencies, and force majeure events.',
    content: [
      'Menza will make reasonable efforts to provide continuous service. However, temporary interruption may occur due to:',
      '• Server maintenance',
      '• Internet/network failure',
      '• Payment gateway failure',
      '• Banking system failure',
      '• Technical problems',
      '• Cybersecurity incidents',
      '• Government or regulatory requirements',
      '• Force majeure events',
      'Menza shall not be liable for interruptions caused by circumstances beyond its reasonable control.',
    ],
  },
  {
    id: 13,
    title: '13. Refund & Cancellation',
    category: 'financial',
    icon: 'RotateCcw',
    summary: 'Subscription refund rules, third-party gateway policies, and unauthorized transaction reporting.',
    content: [
      '1. Cancellation requests shall be handled according to the applicable subscription/refund policy.',
      '2. Fees already paid may not be refundable unless specifically stated.',
      '3. Transactions involving third-party payment gateways shall also be subject to their respective refund policies.',
      '4. Any fraudulent or unauthorized transaction should be reported to Menza immediately.',
    ],
  },
  {
    id: 14,
    title: '14. Account Suspension & Termination',
    category: 'compliance',
    icon: 'UserX',
    summary: 'Conditions under which an account may be suspended or terminated for violations or non-payment.',
    content: [
      'Menza may suspend or terminate an account if:',
      '• The user violates these Terms.',
      '• Fraudulent activity is suspected.',
      '• Payments remain overdue.',
      '• The service is being misused.',
      '• The account creates a security or legal risk.',
      '• Required information or documents are not provided.',
      'Upon termination, access to certain Menza services may immediately cease.',
    ],
  },
  {
    id: 15,
    title: '15. Limitation of Liability',
    category: 'legal',
    icon: 'ShieldAlert',
    summary: 'As-available service provision, exclusion of indirect business losses, and operational boundaries.',
    content: [
      'Menza provides technology and software services on an "as available" basis.',
      'To the maximum extent permitted by applicable law, Menza shall not be liable for indirect, incidental, consequential or business losses arising from:',
      '• Loss of profit',
      '• Loss of business',
      '• Network failure',
      '• Payment gateway failure',
      '• Third-party service failure',
      '• Incorrect information entered by the Restaurant',
      '• Food quality or restaurant operations',
      '• Unauthorized use caused by the user\'s failure to protect credentials',
    ],
  },
  {
    id: 16,
    title: '16. Indemnification',
    category: 'legal',
    icon: 'Shield',
    summary: 'Merchant agreement to indemnify Menza against legal claims, penalties, and violations.',
    content: [
      'The Restaurant/User agrees to indemnify and hold Menza harmless from claims, losses, damages, penalties, costs or expenses arising from:',
      '• Violation of these Terms',
      '• Illegal activities',
      '• Misuse of the platform',
      '• Violation of customer rights',
      '• Incorrect or unlawful business information',
      '• Violation of applicable laws',
    ],
  },
  {
    id: 17,
    title: '17. Changes to Terms',
    category: 'legal',
    icon: 'FileEdit',
    summary: 'Right to update policies, notification channels, and continued usage implying consent.',
    content: [
      'Menza may update these Terms & Conditions from time to time. Updated terms may be published through the Menza website, application or other appropriate communication channels.',
      'Continued use of Menza after an update constitutes acceptance of the revised Terms.',
    ],
  },
  {
    id: 18,
    title: '18. Governing Law & Jurisdiction',
    category: 'legal',
    icon: 'Scale',
    summary: 'Applicability of Indian law and exclusive jurisdiction of competent courts at Bhopal, Madhya Pradesh.',
    content: [
      'These Terms shall be governed by the laws of India.',
      'Subject to applicable law, disputes shall be subject to the jurisdiction of the competent courts at Bhopal, Madhya Pradesh, India.',
    ],
  },
  {
    id: 19,
    title: '19. Contact & Support',
    category: 'general',
    icon: 'Headphones',
    summary: 'Official company contact details, registered office address, email, phone, and web support.',
    content: [
      'For questions, complaints, technical support or legal notices:',
      '• Brand: Menza',
      '• Operated By: QUBENEXUS TECHNOLOGIES PRIVATE LIMITED',
      '• Address: Plot No 31, Sage Suncity Phase-2, Bagroda, Bhopal, Madhya Pradesh, PIN Code: 462026',
      '• Email: support@menza.in',
      '• Phone: +91 9713034109',
      '• Website: www.menza.in',
    ],
  },
  {
    id: 20,
    title: '20. Acceptance',
    category: 'general',
    icon: 'CheckSquare',
    summary: 'Binding confirmation that the user has read, understood, and agreed to all terms and rules.',
    content: [
      'By registering, accessing or using Menza, the Restaurant/User confirms that they have read, understood and agreed to these Terms & Conditions, Rules and Regulations.',
      'Menza — Smart • Simple • Serve',
    ],
  },
];
